sudo: required

language: php

matrix:
  fast_finish: true
  include:
    - env: DBTYPE=mysql
      php: 5.3
    - env: DBTYPE=sqlite
      php: 5.3
    - env: DBTYPE=mysql
      php: 5.5
    - env: DBTYPE=sqlite
      php: 5.5
    - env: DBTYPE=mysql
      php: hhvm
    - env: DBTYPE=sqlite
      php: hhvm

before_script:
  - sudo apt-get update > /dev/null
  - sudo apt-get install -y --force-yes apache2 libapache2-mod-php5 php5-curl php5-mysql php5-intl
  - sudo sed -i -e "s,/var/www,$(pwd)/web,g" /etc/apache2/sites-available/default
  - sudo /etc/init.d/apache2 restart
  - bash ./scripts/travis/before_script.sh

script:
  - bash ./scripts/travis/script.sh

after_success:
  - bash ./scripts/travis/after_script.sh
